"""Render a VoiceProfile as a portable Markdown 'voice guide' for external LLMs."""
from __future__ import annotations

from blogforge.prompt_rules import PromptRule, render_prompt_rules
from blogforge.voice.ai_tells import load_ai_tells
from blogforge.voice.models import VoiceProfile

_PREAMBLE = (
    "> **How to use:** This guide is a portable reference for an AI assistant or\n"
    "> personal writing workflow when you write for me. The paired rules below identify\n"
    "> the constraints\n"
    "> that shape article output."
)


def build_voice_guide(profile: VoiceProfile) -> str:
    ai = load_ai_tells()
    parts: list[str] = [f"# {profile.name or 'My Voice'} — Writing Voice Guide", _PREAMBLE]
    parts.append(render_prompt_rules([
        PromptRule(
            "Follow this voice guide when writing for me.",
            "It records the author's established voice and writing preferences.",
        ),
        PromptRule(
            "Match the persona and style described below.",
            "The persona and style define the author's recognizable voice.",
        ),
        PromptRule(
            "Do not use the words, phrases, or patterns under `Avoid these AI-writing tells.`",
            "These are recurrent style defects that make prose sound machine-generated.",
        ),
        PromptRule(
            "Do not copy the `Rule:` and `Because:` labels or their rationales into "
            "article output.",
            "They are instructions for the writing process, not content for the article.",
        )
    ]))

    persona: list[str] = []
    if profile.persona_identity.strip():
        persona.append(profile.persona_identity.strip())
    if profile.persona_one_line.strip():
        persona.append(f"**In one line:** {profile.persona_one_line.strip()}")
    if profile.persona_tone.strip():
        persona.append(f"**Tone:** {profile.persona_tone.strip()}")
    if persona:
        parts.append("## Persona\n\n" + "\n\n".join(persona))

    style = profile.distilled_style_md.strip()
    parts.append(
        "## My style\n\n" + style if style
        else "## My style\n\n*(Not yet distilled — run distillation on the Voice "
             "screen to capture your style.)*"
    )

    words = [w for w in profile.rules.banished_words if w.strip()]
    phrases = [p for p in profile.rules.banished_phrases if p.strip()]
    if words or phrases:
        b = ["## My banished words & phrases"]
        b.append(render_prompt_rules([
            PromptRule(
                "Do not use the following words and phrases in my writing.",
                "They conflict with the author's established voice and explicit preferences.",
            )
        ]))
        if words:
            b.append(f"Words: {', '.join(words)}")
        if phrases:
            b.append(f"Phrases: {', '.join(phrases)}")
        parts.append("\n".join(b))

    ai_rules = render_prompt_rules([
        PromptRule(
            "Do not use any item in the universal AI-tell word list.",
            "These words are recurrent style defects that make prose sound machine-generated.",
        ),
        PromptRule(
            "Do not use any item in the universal AI-tell phrase list.",
            "These phrases are recurrent style defects that make prose sound machine-generated.",
        ),
        PromptRule(
            "Do not begin sentences with any item in the universal AI-tell opener list.",
            "Repeated stock openers are a recognizable AI-writing tell.",
        ),
        PromptRule(
            "Avoid each structural pattern listed below.",
            "These patterns are recurrent style defects that make prose sound machine-generated.",
        ),
    ])
    parts.append(
        "## Avoid these AI-writing tells\n\n"
        f"{ai_rules}\n\n"
        f"### Words to avoid\n\n{', '.join(ai.words)}\n\n"
        "### Phrases to avoid\n\n" + "\n".join(f"- {p}" for p in ai.phrases) + "\n\n"
        f"### Sentence openers to avoid\n\n{', '.join(ai.sentence_starters)}\n\n"
        f"### Structural patterns to avoid\n\n{ai.patterns.strip()}"
    )

    footer = f"*Generated by BlogForge from {len(profile.samples)} writing samples"
    if profile.distilled_at is not None:
        footer += f" · distilled {profile.distilled_at:%Y-%m-%d}"
    parts.append("---\n\n" + footer + ".*")

    return "\n\n".join(parts) + "\n"
