"""Render a VoiceProfile as a portable Markdown 'voice guide' for external LLMs."""
from __future__ import annotations

from blogforge.voice.ai_tells import load_ai_tells
from blogforge.voice.models import VoiceProfile

_PREAMBLE = (
    "> **How to use:** When you write for me, follow this voice guide — match the\n"
    "> persona and style below, and never use the words, phrases, or patterns under\n"
    '> "Avoid these AI-writing tells." Paste it into any AI assistant as a style\n'
    "> instruction, or keep it as a personal reference."
)


def build_voice_guide(profile: VoiceProfile) -> str:
    ai = load_ai_tells()
    parts: list[str] = [f"# {profile.name or 'My Voice'} — Writing Voice Guide", _PREAMBLE]

    persona: list[str] = []
    if profile.persona_identity.strip():
        persona.append(profile.persona_identity.strip())
    if profile.persona_one_line.strip():
        persona.append(f"**In one line:** {profile.persona_one_line.strip()}")
    if profile.persona_tone.strip():
        persona.append(f"**Tone:** {profile.persona_tone.strip()}")
    if persona:
        parts.append("## Persona\n\n" + "\n\n".join(persona))

    style = profile.distilled_style_md.strip()
    parts.append(
        "## My style\n\n" + style if style
        else "## My style\n\n*(Not yet distilled — run distillation on the Voice "
             "screen to capture your style.)*"
    )

    words = [w for w in profile.rules.banished_words if w.strip()]
    phrases = [p for p in profile.rules.banished_phrases if p.strip()]
    if words or phrases:
        b = ["## My banished words & phrases", "Never use these in my writing:"]
        if words:
            b.append(f"- **Words:** {', '.join(words)}")
        if phrases:
            b.append(f"- **Phrases:** {', '.join(phrases)}")
        parts.append("\n".join(b))

    parts.append(
        "## Avoid these AI-writing tells\n\n"
        "Universal signs of machine-written text. Don't use them.\n\n"
        f"### Words to avoid\n\n{', '.join(ai.words)}\n\n"
        "### Phrases to avoid\n\n" + "\n".join(f"- {p}" for p in ai.phrases) + "\n\n"
        f"### Sentence openers to avoid\n\n{', '.join(ai.sentence_starters)}\n\n"
        f"### Structural patterns to avoid\n\n{ai.patterns.strip()}"
    )

    footer = f"*Generated by BlogForge from {len(profile.samples)} writing samples"
    if profile.distilled_at is not None:
        footer += f" · distilled {profile.distilled_at:%Y-%m-%d}"
    parts.append("---\n\n" + footer + ".*")

    return "\n\n".join(parts) + "\n"
